name: Java Code Style Check

on:
  pull_request:
    branches: [main] # main 브랜치로 향하는 PR에 대해서만 실행

jobs:
  code_style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "21" # 프로젝트에 맞는 Java 버전으로 변경
          distribution: "temurin"

      - name: Run Checkstyle CLI
        run: java -jar tools/checkstyle-10.12.5-all.jar -c checkstyle.xml ${{ github.event.pull_request.head.repo.full_name == github.repository && github.event.pull_request.changed_files.*.endsWith('.java') || github.event.pull_request.head.repo.full_name != github.repository && github.event.pull_request.changed_files.*.endsWith('.java') }}

      # 결과에 따라 PR 상태를 설정 (실패 시 병합 방지)
      - name: Fail if Checkstyle violations are found
        if: failure()
        run: |
          echo "::error::Java 코드 스타일 검사를 통과하지 못했습니다. 자세한 내용은 Checks 탭을 확인해주세요."
          exit 1
