name: Java Code Style Check

on:
  pull_request:
    branches: [main] # 또는 원하는 브랜치
    paths:
      - '**.java' # Java 파일만 감지

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17' # 또는 프로젝트에 맞는 Java 버전

      - name: Download Checkstyle
        run: |
          wget -q https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.11.0/checkstyle-10.11.0-all.jar -O checkstyle.jar
          wget -q https://raw.githubusercontent.com/checkstyle/checkstyle/master/src/main/resources/google_checks.xml -O google_checks.xml

      - name: Run Checkstyle with reviewdog
        run: |
          find . -name "*.java" > java-files.txt
          java -jar checkstyle.jar -c google_checks.xml -f xml $(cat java-files.txt) > checkstyle-result.xml || true
          cat checkstyle-result.xml | reviewdog -f=checkstyle -name="checkstyle" -reporter=github-pr-check -level=warning
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
