name: Java Code Style Check

on:
  pull_request:
    branches: [main]

jobs:
  code_style:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2 # Pull Request의 이전 커밋 포함

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "21"
          distribution: "temurin"

      - name: Download Checkstyle CLI
        run: wget https://github.com/checkstyle/checkstyle/releases/download/checkstyle-10.12.5/checkstyle-10.12.5-all.jar -O tools/checkstyle-10.12.5-all.jar

      - name: Get changed Java files
        id: changed_files
        run: |
          changed_java_files=$(git diff --name-only HEAD^ HEAD | grep '\.java$')
          echo "changed_java_files=$changed_java_files" >> $GITHUB_OUTPUT

      - name: Run Checkstyle CLI
        run: java -jar tools/checkstyle-10.12.5-all.jar -c checkstyle.xml ${{ steps.changed_files.outputs.changed_java_files }}

      - name: Fail if Checkstyle violations are found
        if: failure()
        run: |
          echo "::error::Java 코드 스타일 검사를 통과하지 못했습니다. 자세한 내용은 Checks 탭을 확인해주세요."
          exit 1
